# Generated by Django 4.1.2 on 2022-12-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject')),
                ('message', models.TextField()),
            ],
        ),
    ]
