# Generated by Django 4.1.2 on 2022-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='surname',
        ),
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
