# Generated by Django 4.1.2 on 2022-12-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contactus_subject_remove_contactus_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='House Type')),
            ],
        ),
        migrations.CreateModel(
            name='SubscripedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('conf_digit', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='number')),
                ('rooms', models.IntegerField(verbose_name='Rooms')),
                ('toilet', models.IntegerField(verbose_name='Toilet')),
                ('Bathroom', models.IntegerField(verbose_name='Bathroom')),
                ('description', models.TextField(verbose_name='Description')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image 1')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image 1')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image 1')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.housetype')),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
    ]
