# Generated by Django 4.1.2 on 2023-01-26 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_property_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('authur', models.CharField(max_length=50, verbose_name='Posted By')),
                ('write_up', models.TextField(max_length=500, verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.get_image_filename, verbose_name='Image')),
                ('blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='property',
            name='house_type',
        ),
        migrations.DeleteModel(
            name='SubscripedUsers',
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
