# Generated by Django 4.1.2 on 2023-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_images_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Image'),
        ),
    ]
